inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/DynamicFindBy:
  AllowedReceivers:
    - RSpotify::Playlist
