version: '3.4'

volumes:
  db_data:

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
