version: '3.4'

volumes:
  db_data:
  redis_data:

services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: "production"
      NODE_ENV: "production"
      RAILS_SERVE_STATIC_FILES: "true"
      DB_HOST: "postgres"
  postgres:
    image: postgres:14.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
